kind: GitRepo
apiVersion: fleet.cattle.io/v1alpha1
metadata:
  name: services
  namespace: fleet-default
spec:
  repo: https://github.com/atoy3731/rancher-demo.git
  branch: main
  targets:
  - name: services
    clusterSelector:
      matchLabels:
        env: services
  paths:
  - "./devops/jenkins"
  - "./cloud/aws-cloud-provider"