{{- if .Values.config.nodeportEnabled }}
apiVersion: v1
kind: Service
metadata:
  name: rancher-demo-nodeport
spec:
  type: NodePort
  selector:
    app: demo
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
    nodePort: {{ .Values.config.nodeport }}
{{- end -}}