defaultNamespace: jenkins
helm:
  repo: https://charts.jenkins.io
  chart: jenkins
  version: 4.3.28
  releaseName: jenkins
  values:
    controller:
      ingress:
        enabled: true
        hostName: jenkins.kube.lol
        tls:
        - secretName: kube-lol
          hosts:
            - jenkins.kube.lol

